#!/bin/sh
cd /src/pubkv
COOKIE=$1
if [ "$COOKIE" = "" ]
then
   COOKIE=pubkv
fi
IP=`hostname -i`
NAME=`hostname`
cat > _rel/pubkv_release/releases/1/vm.args <<EOL
-name $NAME@$IP
-setcookie $COOKIE
-mnesia dir '\"./Mnesia\"'
EOL
exec _rel/pubkv_release/bin/pubkv_release console
