#!/bin/sh
cd /src/pubkv
TYPE=$1
SLAVES=$2
if [ "$TYPE" = "node" ]; then cat node-name; exit; fi
if [ "$COOKIE" = "" ]; then COOKIE=pubkv; fi
if [ "$TYPE" = "" ]; then TYPE=master; fi
IP=`hostname -i`
NAME="$TYPE-`hostname`"
cat > _rel/pubkv_release/releases/1/vm.args <<EOL
-name $NAME@$IP
-setcookie $COOKIE
-mnesia dir '\"./Mnesia\"'
EOL
if [ "$TYPE" = "master" ]
then
	cat > _rel/pubkv_release/releases/1/sys.config << EOL
[{ pubkv, [ {type,master}, {slaves,[$SLAVES]} ] }].
EOL
else
	cat > _rel/pubkv_release/releases/1/sys.config << EOL
[{ pubkv, [ {type,slave} ] }].
EOL
fi
echo "$NAME@$IP" > node-name
exec _rel/pubkv_release/bin/pubkv_release console
